### ISSUE TITLE
首页图有问题，只显示部分

### ISSUE THREAD

**Issue by chenbihao** [wxyyxc1992/Coder-Knowledge-Management#8]
[这张图片](https://camo.githubusercontent.com/b341f441c58e1f119d9c20a3b94133482f27f04a81a992e2e2609a780d92ef7f/68747470733a2f2f7069632e696d6764622e636e2f6974656d2f3630376139316634383332326536363735633665356336352e706e67)

视觉效果：
![image](https://user-images.githubusercontent.com/21167262/149248126-ea6458cd-9a1f-4c3d-88a9-98cbb55bf57c.png)

**Comment by jiek233** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您发送的邮件我已收到，我会在看到后尽快回复您。
